### ISSUE TITLE
Allow the usage of a server other than localhost

### ISSUE THREAD

**Issue by bhourigan** [vsco/jsonconsul#26]
I'd like the ability to connect to a consul server other than localhost, it seems that `consul.go` will only use the default configuration options:

```
func init() {
        var (
                err error
        )

        client, err = api.NewClient(api.DefaultConfig())
        if err != nil {
                log.Fatalln(err)
        }
        kv = client.KV()
}
```

**Comment by rodaine** [comment]
Hi @bhourigan! The default configuration passed in here uses the [standard Consul environment variables](https://www.consul.io/docs/agent/options.html):

``` sh
CONSUL_HTTP_ADDR="example.com:8500" jsonconsul ...
```

The readme should be updated to reflect that, however. Thanks for the report!

**Comment by bhourigan** [comment]
Thanks!
